name: Testes

on: [push, pull_request]

jobs:
    Test_in_Linux:
        runs-on: ubuntu-latest

        steps:
            - name: Copiando o repositório
              uses: actions/checkout@v4
              with:
                ref: main

            - name: Instalando o Python e pip
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
                cache: 'pip'

            - name: Instalação das dependências
              # run: pip install -r requirements.txt
              run: pip install .

            - name: Criar diretório temporário
              run: mkdir -p temp

            - name: Rodando os testes
              run: pytest
    
    Test_in_Windows:
      runs-on: windows-latest

      steps:
          - name: Copiando o repositório
            uses: actions/checkout@v4
            with:
              ref: main

          - name: Instalando o Python e pip
            uses: actions/setup-python@v5
            with:
              python-version: '3.12'
              cache: 'pip'

          - name: Instalação das dependências
            # run: pip install -r requirements.txt
            run: pip install .

          - name: Criar diretório temporário
            run: mkdir -p temp

          - name: Rodando os testes
            run: pytest

    Test_in_MacOsX:
      runs-on: macos-latest

      steps:
          - name: Copiando o repositório
            uses: actions/checkout@v4
            with:
              ref: main

          - name: Instalando o Python e pip
            uses: actions/setup-python@v5
            with:
              python-version: '3.12'
              cache: 'pip'

          - name: Instalação das dependências
            # run: pip install -r requirements.txt
            run: pip install .

          - name: Criar diretório temporário
            run: mkdir -p temp

          - name: Rodando os testes
            run: pytest